### PR TITLE
Added addRow function to DataFrame(Returns a DataFrame with old rows …

### PR DESCRIPTION
**Pull request by LeandroC89**
Added function to add row (non-destructive).
I based the logic on the example provided here [https://www.gitmemory.com/issue/holgerbrandl/krangl/76/525598794](url) with added logic.

It is useful for data transformation & validation, and it is what I'm using on my excel sheet reading function too.

PS: This library is awesome, nice work.

### CODE REVIEW

**Comment by holgerbrandl** [comment]
Nice addition. Could you add a short unit-test to cover this feature?

**Comment by LeandroC89** [comment]
Thank you, I'll do so.

**Comment by LeandroC89** [comment]
Added RowTests file with the unit-test for this feature.
(Didn't think it'd fit any of the existing test files but will gladly move it to another file if needed)

Thank you

**Comment by holgerbrandl** [comment]
Thank you so much.

**Pull request merged**
