### PR TITLE
add pctChange

### PR DESCRIPTION
**Pull request by amorphous1**
calculates the percentage change between the current and a prior column value

### CODE REVIEW

**Comment by holgerbrandl** [comment]
Thanks, @amorphous1 for this great analysis and contribution.

pctChange and joins could have been separate PRs. In particular, since `pctChange` should be merged right away but the joins require some more discussion analysis I think.

 **Regarding pctChange**

I think it would even better if we could rather (or in addition) develop a `lead`/`lag` as in https://dplyr.tidyverse.org/reference/lead-lag.html . I have used these methods (yet in R) a gazillion times to implement pctChange and even more for time-series analysis. E.g. once we have lead/lag we could also have `diff` almost for free https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/diff

So maybe we/you could evolve `paddedNeighbouringValues` into lead/lag?

**Joins**

Wonderful work here. Although I'm using joins daily, this was my first _actual_ implementation , so there's certainly lots of room for improvement. I've added some commits to essentially preserve the first half where you correctly proposed to just do `cartesianProductWithoutBy` when is actually needed.

However, I've rolled back the mutable df (for now) for various reasons
* My own Microbenchmark in `JoinBenchmarking.kt` did not use warmup runs (corrected now in this branch) which greatly affects results
* I could not reproduce a significant performance improvement compared to `bindRows` (which is now used in this branch)
* MutableDataFrame reimplements functionality in particular  `bindRows` 
* If you could propose a more efficient way to bind dataframes, we should refactor `bindRows` instead because many other parts of the API would benefit as well.

I hope this makes, if not feel welcome to comment in here, or we could also schedule a chat in https://gitter.im/holgerbrandl/krangl

What do you think?

**Comment by holgerbrandl** [comment]
Also, we/I need to develop some more streamlined workflow to persist performance regression results into the repo and to automate performance snapshots at least on release level.

Your approach of using source comments to inline a performance regression result table indicate a need here. :-)  

Conceptually these performance regressions could be even part of the tests, but it's impossible to define runtime limits for tests that will inevitably run on different computers. So I guess, we would need 2 scripts/classes
1. One script to actually run all performance regression tests and to write the results (using the commit hash or a custom label as filename) into the repo (e.g. into a dedicated directory `perf_regression`)
2. A second script to simply merge all existing data and produce some report with trends and warnings.

I wonder how other similar repos (pandas, dplyr, tablesaw) handle this challenge?

**Comment by amorphous1** [comment]
Oops, those should definitely be two PRs, probably inexperience with GitHub on my part. Here's what I did:

- Wednesday
  - committed "add pctChange" to my fork
  - opened a PR via GitHub's CLI ("gh pr create")
  - verified the PR showed up and contained my (single) commit
- Thursday/Friday
  - looked into the performance
  - pushed two more commits to my fork
  - (did not yet open a PR for this because I wanted to add some commentary)

I had no idea the second push would affect my existing PR, will keep that in mind for the future. If you know of a way to take these commits out of this PR feel free to do so, I never intended them to show up here.

**Comment by amorphous1** [comment]
**regarding pctChange**

For context: I was translating a "real-world" Jupyter notebook using Python/Pandas to Kotlin/Krangl. That notebook made use of cumsum [1] and pct_change [2]. For the former, the cumSum implementation you had added just a couple days earlier was exactly what I needed. For the latter, I used the pandas API docs as a reference and implemented just enough for my use case.

Evolving it to support more use cases sounds reasonable. I'm happy to look into it myself if I find the time, but can't promise anything.

[1] https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.cumsum.html
[2] https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pct_change.html

**Comment by holgerbrandl** [comment]
What do you think about my revision of your PR: Are you fine with that or do you see any downsides of changing it to use `bindRows` instead of your proposed MutabableDF?

**Comment by amorphous1** [comment]
**Regarding performance improvements**

For context: In the Jupyter notebook mentioned above I had to (inner) join two data frames with 500k and 5k rows, respectively. This took a couple of seconds in Pandas but over 15 minutes in Krangl (although it did eventually finish with the same result). With the change I proposed I got that same join down to a couple of seconds as well.

I re-tested with your tweaks and it is still fast enough, no noticeable difference (and the JoinBenchmarking kind of agrees). I'm happy with your revision - I only used a MutableDataFrame because that was the only way I could come up with. Your solution has the advantage of avoiding those unchecked casts (something I was planning to mention in the second PR for the performance changes).

**Regarding performance testing results**

I have no idea about other data science repos, but read about how the Scala compiler handles this a while ago [1]. They have a pretty fancy dashboard [2] and use a dedicated machine for performance tests. Probably not something that's easy to fully replicate, but it could give some inspiration. 

[1] https://www.lightbend.com/blog/scala-compile-faster 
[2] https://scala-ci.typesafe.com/grafana/dashboard/db/scala-benchmark?orgId=1

**Comment by holgerbrandl** [comment]
Concerning performance benchmarking: I've just noticed that I had started some rather elaborate setup in https://github.com/holgerbrandl/krangl/blob/master/examples/benchmarking using JMH including some reporting. Clearly there should be more regressions (like for joining) and release automation is missing as well.

**Pull request merged**
